### ISSUE TITLE
Home Assistant Repository

### ISSUE THREAD

**Issue by jflecool2** [zajac-grzegorz/homeassistant-addon-cups-airprint#1]
Hello,
First, thanks for making this. 
However, most people (myself included) use "Addons" -> "Repositories" -> "Add" to install new repo/addons. 
Yours doesn't have the right format to allow that (files like repository.json). 
Could you please change the file structure to allow that?
Thank you

**Comment by jflecool2** [comment]
Bonus for adding [this button](https://camo.githubusercontent.com/41f3bdc5089cfc40e3e29fc695beb8e053e515c0aee09243ed13a9d565f5583b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4164642532307265706f7369746f7279253230746f2532306d792d486f6d65253230417373697374616e742d3431424446353f6c6f676f3d686f6d652d617373697374616e74267374796c653d666f722d7468652d6261646765) on your github readme file

**Comment by zajac-grzegorz** [comment]
> Hello, First, thanks for making this. However, most people (myself included) use "Addons" -> "Repositories" -> "Add" to install new repo/addons. Yours doesn't have the right format to allow that (files like repository.json). Could you please change the file structure to allow that? Thank you

done.
