### ISSUE TITLE
Add brother printer drivers to image

### ISSUE THREAD

**Issue by wigster** [zajac-grzegorz/homeassistant-addon-cups-airprint#18]
Hi

Could I please ask you to add the brother printer drivers for some legacy printers to the dockerfile:

Tha package is `printer-driver-brlaser`. It's github page is here:

https://github.com/pdewacht/brlaser

I can add it inside the container easily and everything works, but it's not permanent and I do not know how to modify it in HAOS. 

Thanks!

**Comment by zajac-grzegorz** [comment]
Added required drivers
