### ISSUE TITLE
configuration is not persistent

### ISSUE THREAD

**Issue by kissi7** [zajac-grzegorz/homeassistant-addon-cups-airprint#4]
I am using HA OS, than I added repository and installed addon.

I added printer (of course I had to reset password for user "print" and allow "all" to be able connect to :631 port as @local is not sufficient) but after the reboot of HA all confings are gone. Is this common behaviour or bug as it should store all changes in /config/... ?

**Comment by zajac-grzegorz** [comment]
The storage to /config folder is not implemented yet. Once I find some time this will be added.

**Comment by zajac-grzegorz** [comment]
> I am using HA OS, than I added repository and installed addon.
> 
> I added printer (of course I had to reset password for user "print" and allow "all" to be able connect to :631 port as @Local is not sufficient) but after the reboot of HA all confings are gone. Is this common behaviour or bug as it should store all changes in /config/... ?

Configuration is now persisted in the /data/cups folder. That folder maps to the docker volume managed by the Supervisor.

**Comment by romeocontrol** [comment]
Hello,
I am a little on the tube:
Where on earth is this /date/cups folder located at homeassistant?
Stupid question, I would still be very very grateful for an answer.
Many greetings 
RT

**Comment by zajac-grzegorz** [comment]
> Hello,
> 
> I am a little on the tube:
> 
> Where on earth is this /date/cups folder located at homeassistant?
> 
> Stupid question, I would still be very very grateful for an answer.
> 
> Many greetings 
> 
> RT

By Hassio design it is not visible to the  users, it is private to the Docker image that owns it. However it can be accessed indirectly, I know 2 methods:
1. From a bash shell run within the hassio_supervisor container
2. SSH to the Hassio operating system, then it is available in /mnt/data/supervisor...

More details is here:

https://developers.home-assistant.io/docs/operating-system/debugging/

And here:

https://developers.home-assistant.io/docs/operating-system/partition
